# Project information
site_name: "Hacktoberfest Swag List 2022"
site_description: "Connecting contributors to open-source projects during Hacktoberfest"
site_author: "crweiner"
site_url: "https://hacktoberfestswaglist.com"

site_name: Hacktoberfest Swag List
docs_dir: "docs"
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/crweiner/hacktoberfest-swag-list"
edit_uri: "https://github.com/crweiner/hacktoberfest-swag-list/edit/master/docs"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - git-revision-date-localized
  - mkdocs_pymdownx_material_extras
